### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by liberodark**
Better to no add .exe for cross plateform project

### CODE REVIEW

**Comment by liberodark** [comment]
Probably add in gitignore : rh.exe would be great better for no expand size

**Comment by essial** [comment]
Rh.exe is needed for CI build automation to set windows release app icon.

**Comment by liberodark** [comment]
yes but OpenDiablo.exe is not necessary for CI

**Comment by essial** [comment]
Yeah, I agree with the OpenDiablo2.exe part, that was an issue we found last night. Just making sure you know we DO need rh.exe.

**Pull request merged**
