### PR TITLE
data encoding: DC6

### PR DESCRIPTION
**Pull request by gucio321**
Hi there
this is related with #909 and https://github.com/OpenDiablo2/HellSpawner/issues/81

### CODE REVIEW

**Review by gravestench — DISMISSED** [review]

**Comment by gravestench** [comment]
This is breaking tests
```
FAIL	github.com/OpenDiablo2/OpenDiablo2/d2common/d2datautils [build failed]]
FAIL	github.com/OpenDiablo2/OpenDiablo2/d2common/d2loader	0.063s
```

**Comment by gucio321** [comment]
yah, I've removed PushByte method
i'll correct

**Review by gravestench — APPROVED** [review]

**Comment by gravestench** [comment]
there's lint errors, now.

**Comment by gucio321** [comment]
yah, lint errors are on OpenDiablo2:master.

**Pull request merged**
