### PR TITLE
Add close buttons to all panels

### PR DESCRIPTION
**Pull request by juander-ux**
Hi,

this is a small cleanup after my skilltree panel PR. It just adds the close buttons to all panels. While at it I fixed two minor linter cleanup mistakes. Is it possible to run the linter automatically on PR, so that we catch the problems before they get merged?

Cheers

### CODE REVIEW

**Comment by essial** [comment]
Once all lint errors are removed we will enforce linting on all PRs. When we started linting we had thousands of issues so there was no way to enforce it. I think thanks to grav we are getting close!

**Comment by ThomasChr** [comment]
If wanted I can try to get a CI working. But that‘s something @essial need to do.

**Comment by ThomasChr** [comment]
@essial 
Didn‘t read your message before posting mine. Yes, ci would be great!

**Comment by juander-ux** [comment]
Are you using [golint](https://github.com/golang/lint)? I'm having a bit of trouble to run a locally from CLI.

**Comment by gravestench** [comment]
@juander-ux get `golangci-lint`

Once installed, you can run from repo root
```
golangci-lint run ./...
```

**Pull request merged**
