### PR TITLE
Added loaders for itemratio.txt, Overlay.txt and UniqueAppellation.txt

### PR DESCRIPTION
**Pull request by BojanoN**
As per issue #634

### CODE REVIEW

**Comment by gravestench** [comment]
see my review comments on previous PR: https://github.com/OpenDiablo2/OpenDiablo2/pull/657#pullrequestreview-459413617

you've already addressed one of my comments.

**Comment by BojanoN** [comment]
@gravestench please take a look again, i went through all your comments and fixed things

**Comment by essial** [comment]
Merge conflict

**Comment by BojanoN** [comment]
@essial resolved

**Pull request merged**
