### PR TITLE
Tooltip refactor

### PR DESCRIPTION
**Pull request by juander-ux**
Hi,

this PR refactors tooltips into their own ui element. Before skill_selection_panel and inventory were creating their own version, replicating a lot of code.

cheers

### CODE REVIEW

**Comment by gravestench** [comment]
We no longer accept PR's that introduce any lint errors. you should install `golangci-lint` and check your branch by running `golangci-lint run ./...` in the repo root.

**Comment by juander-ux** [comment]
Huh? I guess my golangci-lint setup is broken then :)

**Comment by gravestench** [comment]
If you're using goland, you need to add it as a file watcher after installing the plugin (File >> Settings >> Tools >> File Watchers)

**Comment by juander-ux** [comment]
Thanks. I figured it out. Now I get the linter warnings. Though, I disagree with the linter on one statement
```
d2core/d2ui/tooltip.go:140:23: mnd: Magic number: 2, in <operation> detected (gomnd)
        halfW, halfH := maxW/2, maxH/2
                             ^
```
I disagree that this is a magic number. I don't see any benefit in replacing the 2 with a const. If you insist on the linter having the final say, fine. I'm just thinking that this is not a good style, as it just creates noise where the const is defined for no real benefit.

**Comment by juander-ux** [comment]
Hmm, golangci-lint 1.27.0 and 1.31.0 seem to disagree :). I should install 1.27.0 on my machine as well.

**Comment by gravestench** [comment]
If it's an integer you can shift right by 1 to divide by two, or you can specify a nolint directive. I agree, don't need a const for this.

Nolint directive would look like
```golang
// nolint:gomnd // reason for nolint
```

**Comment by juander-ux** [comment]
> If it's an integer you can shift right by 1 to divide by two
I assumed the compiler is clever enough to figure this out. I like clarity more than cleverness :)

> // nolint:gomnd // reason for nolint
Ah cool, let me fix my PR :)

**Comment by gravestench** [comment]
I mean, the `2` here _is a constant_, it wouldn't be the worst thing to actually make it a const within that scope, even if it is a super small gain

**Comment by gravestench** [comment]
Either way, good work, and thank you for working on this. :+1:

**Comment by essial** [comment]
If you wanna get _really_ specific, / 2 doesn't mean much on its own. That being said, silencing this lint error on this line is just fine by me.

**Pull request merged**
