### PR TITLE
Added loaders for compcodes.txt, events.txt and monai.txt

### PR DESCRIPTION
**Pull request by BojanoN**

### CODE REVIEW

**Comment by BojanoN** [comment]
oh, wasnt aware of that. could you please add a note saying that to the loader issue so that others wont waste their time?

**Comment by gravestench** [comment]
It's specified in almost all of the fileguides on phrozen keep that these fields are comments

**Comment by BojanoN** [comment]
somehow that managed to elude me + a lot of these dont have guides, nevermind.
Should i delete those fields?

**Comment by gravestench** [comment]
yeah, we don't need them

**Comment by BojanoN** [comment]
@gravestench done

**Pull request merged**
