### PR TITLE
Improve run/walk/neutral animation handling. Initial parsing of Level…

### PR DESCRIPTION
**Pull request by presiyan-ivanov**
…Detail records. Support for holding mouse buttons.

- Run/walk/neutral positions now map to a different animation mode(and speed) depending if in or out of town.

- Run/walk toggle which can be activated/deactivated with R key.

- Temporary(and incorrect) loading and mapping for LevelDetails records.

- Zone change label which shows the level name from LevelDetailsRecord when the player enters a different zone.

- Allow holding mouse left/right button to repeatedly generate an action.

### CODE REVIEW

**Comment by gravestench** [comment]
I've added a full loader for `levels.txt` records in pull request #373

**Comment by essial** [comment]
Oh man, this may have one hell of a merge issue in a few.. Let me finish my map engine changes and we'll see where that puts this PR.

**Comment by essial** [comment]
Yeah you have some merge issues. Let me know if you need help doing this merge.

**Comment by essial** [comment]
Please add your name to the CONTRIBUTORS file. Once you do I will merge. If you prefer to not have your name in it let me know and I'll merge as is. Thanks for this!

**Pull request merged**
