### PR TITLE
Preliminary ECS work

### PR DESCRIPTION
**Pull request by gravestench**
# What is ECS?
ECS stands for Entity Component System, and it's a departure from the typical object oriented class-inheritance architecture. Basically, all game entities are composed of one or more components, and systems only process entities that have components the system is interested in. Usually, Entities are just unique ID's, components are structs (and have little or no methods), and all of the functional aspects of the game/application are carried out by systems.

# Why ECS?
The ECS architecture should greatly reduce the coupling throughout the code by divvying the functional responsibilities up between systems. This should make the code a lot easier to maintain, refactor, and extend.

# What's an example of how ECS can help us?
Currently, the way that rendering happens in OD2, everything that can render is in charge of how it renders to the screen. At some point, the game screen `Surface` is passed to the player's map entity animation. The animation then renders it's own `Surface` onto the game screen `Surface`. If you look at the code, you'll see that our `Renderer` is a dependency in a lot of places, and I think this is the wrong approach.

All of these rendering calls can be placed into a single `RenderingSystem` which is interested in entities that have a `RenderSurface` and `Position` component, or something similar. In this way, all of the code for rendering is in one system.

To put this into perspective, think about how big of a refactor it would take to implement a headless game server. Even if it wouldn't require a large refactor effort to implement this feature currently, it would be trivial to omit the renderer from the ECS "world" during initialization; the game would simply run, just without a renderer system.

# What is [Akara](https://github.com/gravestench/akara)?
Akara is the bastardized ECS based on java's Artemis, which is based on another ECS framework called Ash. I had initially tried to use a couple other ECS "frameworks" for go, but there's just not much out there for ECS in golang that was easy to use/understand.

**With a lot of help and guidance from our friend and rival @collinsmith** who is working on Riiablo, i was able to slap together an ECS solution that was fairly simple to use and not too complicated. It ended up being generic enough that I felt it deserved its own repo.

I'm nowhere near done with akara and plan on maintaining it.

# How does [Akara](https://github.com/gravestench/akara) work?
Go look at the Readme for the akara repo.

# What's been implemented so far using Akara?
- **Game Config System** - responsible for the initial game bootstrap process. It creates an entity that eventually becomes the loaded (or default) game config. After the game config is loaded, it then sets up the MPQ's from the config file as file sources.
- **File Type Resolver** - responsible for determining the type of a file
- **File Source Resolver** - responsible for creating "file sources", things that can open files as data streams.
- **File Handle Resolver** - responsible for creating (and caching) file handles for file paths by using file sources
- **Asset Loader** - responsible for creating (and caching) game assets (dcc, palettes, wav, string tables, etc)
- **Movement System** - this is a test movement system, just to illustrate how movement could be done. This is not likely what our movement system would actually look like.
- **TimeScale System** - another example, an implementation of our time dilation feature as a system

### CODE REVIEW

**Comment by gravestench** [comment]
The failing test has to do with my local setup, I was testing with actual MPQ sources derived from my config file. You can safely disregard that for the time being.

**Comment by ThomasChr** [comment]
I like the ECS idea, but frankly I didn't understand the code completly.
Your explanation sounds sound, so I think this is the way to go - if it won't take to long to refactor everything and if the Akara dependency is stable enough.

**Comment by gravestench** [comment]
@ThomasChr If it's just me working on this, it will take a long time, no doubt. it's a matter of refactoring most of our existing code. This is why I think it's a _really good  idea_ that we start making feature branches instead of always making PR's straight into master. Other people can help in this effort now that there are examples to work off of.

**Comment by gravestench** [comment]
# Update on ECS effort
I wanted to give an update on the status of this branch just to let everyone know that this is not dead. I've been rebasing off of master regularly, and I think I've been making good progress.

This is what I've been working on this last month:
* reduced boilerplate code required for component declarations
* added "Scene" systems
* added a rendering system
* removed all lint errors in the ecs code
* added the arg `--ecs` for launching the ecs implementation

This is what i'm trying to do next:
* figure out how to do scene render ordering
* add object factory systems for each type of game object
* implement the loading screen as a scene system
* implement the main menu screen as a scene system

## Rendering System
I was able to add a rendering system. The rendering system is fairly simple in that it is only interested in rendering the main viewports of all scenes.

Here is my understanding of what a viewport is:
* a viewport is an entity
* a viewport is something that scenes have at least one of
* a scene's first viewport is always the main viewport
* a viewport entity has a `ViewportComponent` which represents a rectangle in screen-space; moving the rectangle around does not change what gets rendered to the viewport, but it changes where the viewport ges rendered
* a viewport entity has a `CameraComponent` that can be used to translate around the scene to render at different positions and to zoom in and out
* a viewport entity has a `RenderableComponent`, which contains the renderable surface

## Scene Systems
My understanding of a `Scene` and what it should do:
* a scene is a system
* keeps track of one or many viewports
* has one and only one main viewport
* all other viewports are rendered to the main viewport
* keeps track of game objects that belong in the scene
* renders game objects to viewports
* is coupled to a handful of other systems (namely, the `RenderSystem` and `GameObjectFactory` as of now)
* can be paused and unpaused
* can run in parallel with other scenes (since it's a system!)

Basically, a `Scene` is just an implementation of `akara.System`, but with extra stuff. All of the generic functionality that makes a system a `Scene` is contained inside of `BaseScene`:
```golang
// BaseScene encapsulates common behaviors for systems that are considered "scenes",
// such as the main menu, the in-game map, the console, etc.
//
// The base scene is responsible for generic behaviors common to all scenes,
// like initializing the default viewport, or rendering game objects to the viewports.
type BaseScene struct {
	*akara.BaseSystem
	*d2util.Logger
	key         string
	booted      bool
	paused      bool
	systems     *baseSystems
	Add         *sceneObjectFactory
	Viewports   []akara.EID
	GameObjects []akara.EID
	*d2components.ViewportMap
	*d2components.MainViewportMap
	*d2components.ViewportFilterMap
	*d2components.CameraMap
	*d2components.RenderableMap
	*d2components.PositionMap
	*d2components.ScaleMap
	*d2components.AnimationMap
	*d2components.OriginMap
	*d2components.AlphaMap
}
```

## Reduced component boilerplate code
I've done a bit of work to reduce the amount of boilerplate code required to add components and systems to the ECS world. Most of the generic functionality for components and systems have now been tucked away into 
* `akara.BaseSystem`
* `akara.BaseComponent`
* `akara.BaseComponentMap`.

A typical `Component` declaration will look like this:
```golang
// PositionComponent contains an embedded d2vector.Position
type PositionComponent struct {
	*akara.BaseComponent
	*d2vector.Position
}
```

With every `Component` declaration there will also be a `ComponentMap` declaration. The component maps provide the initialization logic for new component instances, as well convenience methods that return the concrete component implementation (as opposed to the generic `Component` interface).
```golang
// PositionMap is a map of entity ID's to Position
type PositionMap struct {
	*akara.BaseComponentMap
}

// AddPosition adds a new PositionComponent for the given entity id and returns it.
// this is a convenience method for the generic Add method, as it returns a
// *PositionComponent instead of an akara.Component
func (cm *PositionMap) AddPosition(id akara.EID) *PositionComponent {
	pos := cm.Add(id).(*PositionComponent)

	p := d2vector.NewPosition(0, 0)

	pos.Position = &p

	return pos
}

// GetPosition returns the PositionComponent associated with the given entity id
func (cm *PositionMap) GetPosition(id akara.EID) (*PositionComponent, bool) {
	entry, found := cm.Get(id)
	if entry == nil {
		return nil, false
	}

	return entry.(*PositionComponent), found
}
```

The `BaseComponent`s are used specifically to:
* store the component ID
* store a function for creating new component instances
* store a function for creating new component map instances

you'll see in the code that a `BaseComponent` is created from these 3 things:
```golang
akara.NewBaseComponent(PositionCID, newPosition, newPositionMap)
```

All of the functions that create components or component maps currently look like this:
```golang
func newPosition() akara.Component {
	return &PositionComponent{
		BaseComponent: akara.NewBaseComponent(PositionCID, newPosition, newPositionMap),
	}
}

func newPositionMap() akara.ComponentMap {
	baseComponent := akara.NewBaseComponent(PositionCID, newPosition, newPositionMap)
	baseMap := akara.NewBaseComponentMap(baseComponent)

	cm := &PositionMap{
		BaseComponentMap: baseMap,
	}

	return cm
}
```

Along with every component, there is a global variable that exists strictly as syntactic sugar; it is an instance of a `BaseComponent` for that component type, and it uses the short singular-form of the component name:
```golang
// Position is a convenient reference to be used as a component identifier
var Position = newPosition() // nolint:gochecknoglobals // global by design
```

These global variables are used during component-injection:
```golang
// MovementSystem handles entity movement based on velocity and position components
type MovementSystem struct {
	*akara.BaseSubscriberSystem
	*d2util.Logger
	*d2components.PositionMap
	*d2components.VelocityMap
}

// Init initializes the system with the given world
func (m *MovementSystem) Init(_ *akara.World) {
	m.Info("initializing ...")

	// try to inject the components we require, then cast the returned
	// abstract ComponentMap back to the concrete implementation
	m.PositionMap = m.InjectMap(d2components.Position).(*d2components.PositionMap)
	m.VelocityMap = m.InjectMap(d2components.Velocity).(*d2components.VelocityMap)
}
```

**Comment by gravestench** [comment]
## ECS Update
I just performed a major refactor of `akara`. Because of the way that component subscriptions work, i need to have unique ID's for each component type. Before, I enumerated all of the component ID's in `d2components` in a big const block. I just figured out how to  remove the need for this, and have made component ID's dynamic.

I have also removed `Component` from the names of all component structs.

## Example: Position component
All that is required of a component now is that it satisfies the `akara.Component` interface:
```golang
// Component can be anything with a `New` method that creates a new component instance
type Component interface {
	New() Component
}
```
The `New` method is where we put component-specific initialization logic.

Here is what the `Position` component currently looks like:
```golang
// Position contains an embedded d2vector.Position, which is a vector with
// helper methods for translating between screen, isometric, tile, and sub-tile space.
type Position struct {
	*d2vector.Position
}

// New creates a new Position. By default, the position is (0,0)
func (*Position) New() akara.Component {
	p := d2vector.NewPosition(0, 0)

	return &Position{
		Position: &p,
	}
}
```

## Example: Registering a component
Becase we no longer manage the component ID, `akara` needs to do it for us. This is done by _registering_ the component in the world:
```golang
type Foo struct {} // a component
type Bar struct {} // a component

config := akara.NewWorldConfig().With(&SomeSystem{})
world := akara.NewWorld(config)

id1 := world.RegisterComponent(&Foo{}) // id will be 0
id2 := world.RegisterComponent(&Foo{}) // id will still be 0
id3 := world.RegisterComponent(&Bar{}) // id will be 1
```

## Example: Retrieving a `ComponentFactory` for creating component instances
Following the previous example:
```golang
type Foo struct {} // a component

config := akara.NewWorldConfig().With(&SomeSystem{})
world := akara.NewWorld(config)

fooID := world.RegisterComponent(&Foo{}) // id will be 0

genericFactory := world.GetComponentFactory(fooID)

e1 := world.NewEntity() // get an entity ID

c := genericFactory.Add(e1) // returns a akara.Component interface
foo := c.(*Foo) // we must cast the interface to our component type
```

## Example: Concrete component factories
I already have several systems that use the same set of components. It really sucks having to cast the generic `akara.Component` interface to concrete component implementations every time you go to retrieve one.

My solution was to create a wrapper struct for each component type, like this:
```golang
// PositionFactory is a wrapper for the generic component factory that returns Position component instances.
// This can be embedded inside of a system to give them the methods for adding, retrieving, and removing a Position.
type PositionFactory struct {
	Position *akara.ComponentFactory
}

// AddPosition adds a Position component to the given entity and returns it
func (m *PositionFactory) AddPosition(id akara.EID) *Position {
	return m.Position.Add(id).(*Position)
}

// GetPosition returns the Position component for the given entity, and a bool for whether or not it exists
func (m *PositionFactory) GetPosition(id akara.EID) (*Position, bool) {
	component, found := m.Position.Get(id)
	if !found {
		return nil, found
	}

	return component.(*Position), found
}
```
**See the `ProcessEntity` method below for the magic!**

## Example: A `Movement` system
Here is what the example `MovementSystem` in `d2core/d2systems` currently looks like:
```golang
// MovementSystem handles entity movement based on velocity and position components
type MovementSystem struct {
	akara.BaseSubscriberSystem
	*d2util.Logger
	d2components.PositionFactory
	d2components.VelocityFactory
	movableEntities *akara.Subscription
}
```
This system only has 3 methods (not including what's in `akara.BaseSubscriberSystem`).

In the `Init` method, we register our components and place the generic factories inside of the concrete factories of the system. Then, we also set up our component subscription (what we iterate over in the `Update` method):
```golang
func (m *MovementSystem) Init(world *akara.World) {
	m.World = world

	m.Logger = d2util.NewLogger()
	m.SetPrefix(logPrefixMovementSystem)

	m.Info("initializing ...")

	positionID := m.RegisterComponent(&d2components.Position{})
	velocityID := m.RegisterComponent(&d2components.Velocity{})

	m.Position = m.GetComponentFactory(positionID)
	m.Velocity = m.GetComponentFactory(velocityID)

	movable := m.NewComponentFilter().Require(
		&d2components.Position{},
		&d2components.Velocity{},
	).Build()

	m.movableEntities = m.AddSubscription(movable)
}
```
When this system gets updated, we want to iterate over entities in our subscription; entities with a `Position` and a `Velocity` component:
```golang
func (m *MovementSystem) Update() {
	for subIdx := range m.Subscriptions {
		entities := m.Subscriptions[subIdx].GetEntities()

		m.Infof("Processing movement for %d entities ...", len(entities))

		for entIdx := range entities {
			m.ProcessEntity(entities[entIdx])
		}
	}
}
```
For each entity in our subscription, we scale the velocity by the time delta (time elapsed since last update), and apply it to the position. **Notice how we are using the methods of the concrete component factories for retrieving components**:
```golang
func (m *MovementSystem) ProcessEntity(id akara.EID) {
	position, found := m.GetPosition(id)
	if !found {
		return
	}

	velocity, found := m.GetVelocity(id)
	if !found {
		return
	}

	s := float64(m.World.TimeDelta) / float64(time.Second)
	position.Vector = *position.Vector.Add(velocity.Vector.Clone().Scale(s))
}
```

**Comment by gravestench** [comment]
Here is a benchmark of the example `MovementSystem`:
```
BenchmarkExampleMovementSystem
BenchmarkExampleMovementSystem/10_entities
BenchmarkExampleMovementSystem/10_entities-8         	 3728889	       288 ns/op
BenchmarkExampleMovementSystem/100_entities
BenchmarkExampleMovementSystem/100_entities-8        	  414553	      2840 ns/op
BenchmarkExampleMovementSystem/1000_entities
BenchmarkExampleMovementSystem/1000_entities-8       	   22266	     54481 ns/op
BenchmarkExampleMovementSystem/10000_entities
BenchmarkExampleMovementSystem/10000_entities-8      	    1333	    814847 ns/op
BenchmarkExampleMovementSystem/100000_entities
BenchmarkExampleMovementSystem/100000_entities-8     	      92	  11266814 ns/op
BenchmarkExampleMovementSystem/1000000_entities
BenchmarkExampleMovementSystem/1000000_entities-8    	       1	2169197837 ns/op
```

**Comment by gravestench** [comment]
I just added `Interactive` components, and an `InputSystem` that handles input logic and subscribes to interactive components. Here's an example of the interactive component in action:
```golang
func (s *MainMenuScene) createTrademarkScreen() {
	s.Info("creating trademark screen")

	imgPath := d2resource.TrademarkScreen
	palPath := d2resource.PaletteSky

	s.sprites.trademark = s.Add.SegmentedSprite(0, 0, imgPath, palPath, 4, 3, 0)

	interactive := s.AddInteractive(s.sprites.trademark)

	interactive.InputVector.SetMouseButton(d2input.MouseButtonLeft)

	interactive.Callback = func() bool {
		s.Info("hiding trademark sprite")

		alpha, _ := s.GetAlpha(s.sprites.trademark)
		alpha.Alpha = 0

		interactive.Enabled = false

		return true // prevent propagation
	}
}
```

And here's how the input system is handling this:
```golang
// Update will iterate over interactive entities
func (m *InputSystem) Update() {
	m.updateInputState()

	for _, id := range m.interactives.GetEntities() {
		preventPropagation := m.applyInputState(id)
		if preventPropagation {
			break
		}
	}
}
```
```golang
func (m *InputSystem) updateInputState() {
	var keysToCheck = []d2input.Key{
		d2input.Key0, d2input.Key1, d2input.Key2, d2input.Key3, d2input.Key4, d2input.Key5, d2input.Key6,
		d2input.Key7, d2input.Key8, d2input.Key9, d2input.KeyA, d2input.KeyB, d2input.KeyC, d2input.KeyD,
		d2input.KeyE, d2input.KeyF, d2input.KeyG, d2input.KeyH, d2input.KeyI, d2input.KeyJ, d2input.KeyK,
		d2input.KeyL, d2input.KeyM, d2input.KeyN, d2input.KeyO, d2input.KeyP, d2input.KeyQ, d2input.KeyR,
		d2input.KeyS, d2input.KeyT, d2input.KeyU, d2input.KeyV, d2input.KeyW, d2input.KeyX, d2input.KeyY,
		d2input.KeyZ, d2input.KeyApostrophe, d2input.KeyBackslash, d2input.KeyBackspace,
		d2input.KeyCapsLock, d2input.KeyComma, d2input.KeyDelete, d2input.KeyDown,
		d2input.KeyEnd, d2input.KeyEnter, d2input.KeyEqual, d2input.KeyEscape,
		d2input.KeyF1, d2input.KeyF2, d2input.KeyF3, d2input.KeyF4, d2input.KeyF5, d2input.KeyF6,
		d2input.KeyF7, d2input.KeyF8, d2input.KeyF9, d2input.KeyF10, d2input.KeyF11, d2input.KeyF12,
		d2input.KeyGraveAccent, d2input.KeyHome, d2input.KeyInsert, d2input.KeyKP0,
		d2input.KeyKP1, d2input.KeyKP2, d2input.KeyKP3, d2input.KeyKP4, d2input.KeyKP5,
		d2input.KeyKP6, d2input.KeyKP7, d2input.KeyKP8, d2input.KeyKP9,
		d2input.KeyKPAdd, d2input.KeyKPDecimal, d2input.KeyKPDivide, d2input.KeyKPEnter,
		d2input.KeyKPEqual, d2input.KeyKPMultiply, d2input.KeyKPSubtract, d2input.KeyLeft,
		d2input.KeyLeftBracket, d2input.KeyMenu, d2input.KeyMinus, d2input.KeyNumLock,
		d2input.KeyPageDown, d2input.KeyPageUp, d2input.KeyPause, d2input.KeyPeriod,
		d2input.KeyPrintScreen, d2input.KeyRight, d2input.KeyRightBracket,
		d2input.KeyScrollLock, d2input.KeySemicolon, d2input.KeySlash,
		d2input.KeySpace, d2input.KeyTab, d2input.KeyUp,
	}

	var modifiersToCheck = []d2input.Modifier{
		d2input.ModAlt, d2input.ModControl, d2input.ModShift,
	}

	var buttonsToCheck = []d2input.MouseButton{
		d2input.MouseButtonLeft, d2input.MouseButtonMiddle, d2input.MouseButtonRight,
	}

	for _, key := range keysToCheck {
		truth := m.inputService.IsKeyPressed(d2enum.Key(key))
		m.inputState.KeyVector.Set(key, truth)
	}

	for _, mod := range modifiersToCheck {
		truth := m.inputService.IsKeyPressed(d2enum.Key(mod))
		m.inputState.ModifierVector.Set(mod, truth)
	}

	for _, btn := range buttonsToCheck {
		truth := m.inputService.IsMouseButtonPressed(d2enum.MouseButton(btn))
		m.inputState.MouseButtonVector.Set(btn, truth)
	}
}
```
```golang
func (m *InputSystem) applyInputState(id akara.EID) (preventPropagation bool) {
	v, found := m.GetInteractive(id)
	if !found {
		return false
	}

	if !v.Enabled || !m.inputState.Contains(v.InputVector) {
		return false
	}

	return v.Callback()
}

```

**Comment by gravestench** [comment]
Here's what the logging output looks like currently:
```
[App Bootstrap][INFO] initializing ...
[App Bootstrap][INFO] setting up component subscriptions
[App Bootstrap][INFO] setting up component factories
[App Bootstrap][INFO] injecting file type resolution system
[File Type Resolver][INFO] initializing ...
[App Bootstrap][INFO] injecting file source resolution system
[File Source Resolver][INFO] initializing ...
[File Source Resolver][INFO] setting up component subscriptions
[File Source Resolver][INFO] setting up component factories
[File Source Resolver][INFO] ... initialization complete!
[App Bootstrap][INFO] injecting file handle resolution system
[File Handle Resolver][INFO] initializing ...
[File Handle Resolver][INFO] setting up component subscriptions
[File Handle Resolver][INFO] setting up component factories
[File Handle Resolver][INFO] ... initialization complete!
[App Bootstrap][INFO] injecting game configuration system
[Game Config][INFO] initializing ...
[Game Config][INFO] setting up component factories
[Game Config][INFO] setting up component subscriptions
[App Bootstrap][INFO] injecting asset loader system
[Asset Loader System][INFO] initializing ...
[Asset Loader System][INFO] setting up component subscriptions
[Asset Loader System][INFO] setting up component factories
[App Bootstrap][INFO] injecting game object factory system
[Object Factory][INFO] initializing ...
[Object Factory][INFO] creating sprite factory
[Object Factory][INFO] initializing sprite factory ...
[App Bootstrap][INFO] setting up local directory /tmp for processing
[App Bootstrap][INFO] setting up user config directory /home/dk/.config/OpenDiablo2 for processing
[App Bootstrap][INFO] setting up config file `config.json` for processing
[App Bootstrap][INFO] ... initialization complete!
[Game Client Bootstrap][INFO] initializing ...
[Game Client Bootstrap][INFO] injecting render system
[Render System][INFO] initializing ...
[Game Client Bootstrap][INFO] injecting input system
[Input System][INFO] initializing ...
[Input System][INFO] setting up component factories
[Input System][INFO] setting up component subscriptions
[Game Client Bootstrap][INFO] injecting update counter system
[Update Counter][INFO] initializing
[Game Client Bootstrap][INFO] injecting loading scene
[Loading][INFO] initializing ...
[Loading][INFO] setting up component subscriptions
[Game Client Bootstrap][INFO] injecting main menu scene
[Main Menu][INFO] initializing ...
[Game Client Bootstrap][INFO] injecting mouse cursor scene
[Mouse Cursor][INFO] initializing ...
[Game Client Bootstrap][INFO] initialization complete
[File Source Resolver][INFO] using FILESYSTEM source for `/tmp`
[File Source Resolver][INFO] using FILESYSTEM source for `/home/dk/.config/OpenDiablo2`
[File Handle Resolver][INFO] resolved `config.json` with source `/home/dk/.config/OpenDiablo2`
[Game Config][INFO] loading config file ...
[Game Client Bootstrap][INFO] game client bootstrap complete, deactivating
[Render System][INFO] creating renderer instance
[Render System][INFO] starting game loop ...
[App Bootstrap][INFO] found 1 new configs to parse
[App Bootstrap][INFO] adding mpq's from config file
[App Bootstrap][INFO] adding mpq: /storage/mpq/patch_d2.mpq
[App Bootstrap][INFO] adding mpq: /storage/mpq/d2exp.mpq
[App Bootstrap][INFO] adding mpq: /storage/mpq/d2xmusic.mpq
[App Bootstrap][INFO] adding mpq: /storage/mpq/d2xtalk.mpq
[App Bootstrap][INFO] adding mpq: /storage/mpq/d2xvideo.mpq
[App Bootstrap][INFO] adding mpq: /storage/mpq/d2data.mpq
[App Bootstrap][INFO] adding mpq: /storage/mpq/d2char.mpq
[App Bootstrap][INFO] adding mpq: /storage/mpq/d2music.mpq
[App Bootstrap][INFO] adding mpq: /storage/mpq/d2sfx.mpq
[App Bootstrap][INFO] adding mpq: /storage/mpq/d2video.mpq
[App Bootstrap][INFO] adding mpq: /storage/mpq/d2speech.mpq
[App Bootstrap][INFO] app bootstrap complete, deactivating system
[File Source Resolver][INFO] using MPQ source for `/storage/mpq/patch_d2.mpq`
[File Source Resolver][INFO] using MPQ source for `/storage/mpq/d2exp.mpq`
[File Source Resolver][INFO] using MPQ source for `/storage/mpq/d2xmusic.mpq`
[File Source Resolver][INFO] using MPQ source for `/storage/mpq/d2xtalk.mpq`
[File Source Resolver][INFO] using MPQ source for `/storage/mpq/d2xvideo.mpq`
[File Source Resolver][INFO] using MPQ source for `/storage/mpq/d2data.mpq`
[File Source Resolver][INFO] using MPQ source for `/storage/mpq/d2char.mpq`
[File Source Resolver][INFO] using MPQ source for `/storage/mpq/d2music.mpq`
[File Source Resolver][INFO] using MPQ source for `/storage/mpq/d2sfx.mpq`
[File Source Resolver][INFO] using MPQ source for `/storage/mpq/d2video.mpq`
[File Source Resolver][INFO] using MPQ source for `/storage/mpq/d2speech.mpq`
[Game Client Bootstrap][INFO] game client bootstrap complete, deactivating
[Loading][INFO] base scene booting ...
[Loading][INFO] setting up component factories
[Loading][INFO] creating default viewport
[Loading][INFO] base scene booted!
[Main Menu][INFO] base scene booting ...
[Main Menu][INFO] setting up component factories
[Main Menu][INFO] creating default viewport
[Main Menu][INFO] base scene booted!
[Mouse Cursor][INFO] base scene booting ...
[Mouse Cursor][INFO] setting up component factories
[Mouse Cursor][INFO] creating default viewport
[Mouse Cursor][INFO] base scene booted!
[Update Counter][INFO] 2 updates per second
[Loading][INFO] creating loading screen
[Loading -> Object Factory][INFO] creating sprite: loadingscreen.dc6, /data/global/palette/loading/pal.dat
[Main Menu][INFO] creating background
[Main Menu -> Object Factory][INFO] creating segmented sprite: gameselectscreenEXP.dc6, /data/global/palette/sky/pal.dat
[Main Menu][INFO] creating buttons
[Main Menu][INFO] creating trademark screen
[Main Menu -> Object Factory][INFO] creating segmented sprite: trademarkscreenEXP.dc6, /data/global/palette/sky/pal.dat
[Mouse Cursor][INFO] creating mouse cursor
[Mouse Cursor -> Object Factory][INFO] creating sprite: ohand.DC6, /data/global/palette/units/pal.dat
[File Handle Resolver][INFO] resolved `/data/global/ui/Loading/loadingscreen.dc6` with source `/storage/mpq/d2data.mpq`
[File Handle Resolver][INFO] resolved `/data/global/palette/loading/pal.dat` with source `/storage/mpq/d2data.mpq`
[File Handle Resolver][INFO] resolved `/data/global/ui/FrontEnd/gameselectscreenEXP.dc6` with source `/storage/mpq/d2exp.mpq`
[File Handle Resolver][INFO] resolved `/data/global/palette/sky/pal.dat` with source `/storage/mpq/d2data.mpq`
[File Handle Resolver][INFO] resolved `/data/global/ui/FrontEnd/trademarkscreenEXP.dc6` with source `/storage/mpq/d2exp.mpq`
[File Handle Resolver][INFO] resolved `/data/global/ui/CURSOR/ohand.DC6` with source `/storage/mpq/d2data.mpq`
[File Handle Resolver][INFO] resolved `/data/global/palette/units/pal.dat` with source `/storage/mpq/d2data.mpq`
[Asset Loader System][INFO] Loading DC6: /data/global/ui/Loading/loadingscreen.dc6
[Asset Loader System][INFO] Loading palette: /data/global/palette/loading/pal.dat
[Asset Loader System][INFO] Loading DC6: /data/global/ui/FrontEnd/gameselectscreenEXP.dc6
[Asset Loader System][INFO] Loading palette: /data/global/palette/sky/pal.dat
[Asset Loader System][INFO] Loading DC6: /data/global/ui/FrontEnd/trademarkscreenEXP.dc6
[Asset Loader System][INFO] Loading DC6: /data/global/ui/CURSOR/ohand.DC6
[Asset Loader System][INFO] Loading palette: /data/global/palette/units/pal.dat
[Update Counter][INFO] 55 updates per second
[Update Counter][INFO] 60 updates per second
[Main Menu][INFO] hiding trademark sprite
[Update Counter][INFO] 60 updates per second
```

**Pull request merged**
