### PR TITLE
asset manager: merged TranslateLabel to TranslateString

### PR DESCRIPTION
**Pull request by gucio321**

### CODE REVIEW

**Comment by gucio321** [comment]
test failed, because OpenDiablo2:master contains lint errors.

**Review by essial — APPROVED** [review]

**Comment by gravestench** [comment]
This is breaking tests in `d2datautils`
```
FAIL	github.com/OpenDiablo2/OpenDiablo2/d2common/d2datautils [build failed]
```

**Comment by gucio321** [comment]
> This is breaking tests in `d2datautils`
> 
> ```
> FAIL	github.com/OpenDiablo2/OpenDiablo2/d2common/d2datautils [build failed]
> ```

fixed in #1039. It was caused by #1038

**Comment by essial** [comment]
There seems to be one final lint error.

**Comment by gucio321** [comment]
ok, no more lints

**Review by essial — APPROVED** [review]

**Pull request merged**
