### PR TITLE
Position implemented in newMapEntity.

### PR DESCRIPTION
**Pull request by danhale-git**
This PR makes the use of pointers consistent in `Vector` and implements `Position` in newMapEntity.
Odd mix of changes I'm afraid but they are all straightforward.

### CODE REVIEW

**Comment by danhale-git** [comment]
I can make NewVector and Clone return pointers. I do still need to learn how to properly profile Vector and Position, now that they are being used.

I'll make the change tomorrow morning in about 10 hours.

**Comment by danhale-git** [comment]
I will do that in a new branch. Feel free to merge this if it's good.

**Comment by essial** [comment]
Merge conflicts. Also I agree we should return pointers so we can chain them.

**Comment by danhale-git** [comment]
This should be two PRs. I'm going to rewrite from a fresh branch and submit the Vector changes separately. I will change all the method return values to pointers this time.

**Pull request closed without merging**
