### PR TITLE
general refactor of text dictionary encoder

### LINKED ISSUE #1054: editing string tables
Already, we have data encoder in d2common/d2fileformats/d2tbl, but we are still unable to edit it. We need to write `AddEntry()` and `DeleteEntry()` methods for TextDIctionary.

reffers to #909 , #1040 and https://github.com/OpenDiablo2/HellSpawner/issues/86

### PR DESCRIPTION
**Pull request by gucio321**
Hi there,
written by me text dictionary encoder was extremely ineffectual, because we was unable to add and remove entries from table.
In this PR I've completely removed my previous encoder and written `d2tbl.Marshal` method again.
also, this fixes #1054, because now we can simply
```golang
if _, ok := dict[key]; !ok {
     dict[key] = newValue
} 
```
this is also related with #909 and https://github.com/OpenDiablo2/HellSpawner/issues/86
the only weak point of this solution is the inability to use newly coded dictionaries in original d2

In this PR I've also added more descriptive error mesages to LoadTextDictionary

it adds unit test for text dictionary too

### CODE REVIEW

**Comment by gucio321** [comment]
image

**Review by gravestench — APPROVED** [review]

**Comment by gravestench** [comment]
> the only weak point of this solution is the inability to use newly coded dictionaries in original d2

Why?

**Comment by gucio321** [comment]
there are several fields, where I just push `0`, because our decoder doesn't use thes bytes. however it **might** be important in retail D2.

**Comment by gucio321** [comment]
other words:
current encoder:
\+ encoded data **probably** could be used in original D2
\- realy hard to edit
\- many redundant fields in dictionary's structure

this PR:
\+ realy independent encoder (in fact could be used on any `map[string]string`)
\+ extremely easy to edit (just add key-value to map)
\- **probably** cannot use in retail D2

**Pull request merged**
