### PR TITLE
Fix Folder location

### PR DESCRIPTION
**Pull request by liberodark**

### CODE REVIEW

**Comment by essial** [comment]
When I get home this afternoon I’ll figure out what to do about the base path, I’ll need to see what Mac users need this set to.

**Comment by essial** [comment]
Looks like the base path should be based on os.UserConfigDir. Make that change and I'll accept the PR.

**Comment by liberodark** [comment]
Yes but all configuration of software or games is in .config not is home is not great.

**Comment by Ziemas** [comment]
`os.UserConfigDir` respects the XDG Base Directory specification and will use `$XDG_CONFIG_HOME` or `~/.config/` if that variable is unspecified.

We can probably use it for other platforms as well as per follows

> On Darwin, it returns $HOME/Library/Application Support. On Windows, it returns %AppData%. On Plan 9, it returns $home/lib.

**Comment by AlexanderEkdahl** [comment]
+1 for `UserConfigDir`. Works well on macOS.

**Pull request closed without merging**
