### PR TITLE
Inital skilltree panel implementation

### PR DESCRIPTION
**Pull request by juander-ux**
Hi,

this PR handles:

* Refactoring of the panel frame into its own class
* Fixing a rendering bug of the inventory for druid/assassin
* Assigning class skills to all characters
* Add an initial skilltree panel where one can click through the tabs and see all the skillicons

foo

Cheers

### CODE REVIEW

**Comment by essial** [comment]
Great work! If you haven't already, make a PR to add your name to the contributors so it shows up in the credits as well!

**Comment by gravestench** [comment]
Good job, loving how tidy this PR is. 

Consider joining the discord. :)

**Comment by juander-ux** [comment]
Thanks. I just saw that you squashed all my commits into one. Do you do that to all PRs? It takes a considerable amount of time for me to separate my changes into logical steps that contain the why. Squashing them defeats the purpose of me doing this. If you always squash them, then it's no a big deal, I would just like to avoid unnecessary work.

Cheers

**Comment by gravestench** [comment]
@juander-ux I think it's out of habit that the PR's get squashed. I'm sorry about this.

@essial I think we should look out for good PR's like this. @juander-ux clearly invested a lot of time and effort to make his commits coherent, and we've just shit on his hard work. We should not have squashed these.

**Comment by essial** [comment]
Technically speaking, each commit should have been its own PR if they were supposed to be tracked as separate commits on this repo. If we're wanting to do a multi un-squashed PR commit, please let me know in the PR comments as this is not the default mode of operation.

**Comment by juander-ux** [comment]
> If we're wanting to do a multi un-squashed PR commit, please let me know in the PR comments as this is not the default mode of operation.

Sounds good to me. I will do that for the bigger PRs :)

**Pull request merged**
